#!/bin/bash
now=$(date +"%d.%m.%Y")
report="/tmp/ccloud-apikey-"${now}".txt"

echo "search for servive accounts having no API key..."
# check if standard clusters are running login
/usr/local/bin/confluent login >/dev/null

# get alles API Keys
/usr/local/bin/confluent api-key list -o json > /tmp/key_list.json 2>/dev/null

# get all service accounts
/usr/local/bin/confluent iam service-account list -o json > /tmp/serviceaccount_list.json 2>/dev/null

# Call API key analytics
echo "please wait, the analysis will take a while..."
/usr/local/bin/python3 /confluent-cli/sa-analytics.py /tmp/key_list.json /tmp/serviceaccount_list.json > $report

echo "Service Account analysis finished"

